# Generated by Django 4.0.3 on 2022-05-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='manager',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='merchandiser',
            old_name='name',
            new_name='user',
        ),
    ]
