# Generated by Django 4.0.3 on 2022-04-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandiser',
            name='route',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='merchandiser',
            name='username',
            field=models.CharField(max_length=40),
        ),
    ]
