# Generated by Django 4.0.3 on 2022-04-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_alter_merchandiser_route_alter_merchandiser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
