# Generated by Django 4.0.3 on 2022-04-27 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_rename_route_routes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Routes',
            new_name='Address',
        ),
    ]
