# Generated by Django 4.0.3 on 2022-04-27 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0005_remove_merchandiser_route_comment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='route',
        ),
    ]
