# Generated by Django 4.0.3 on 2022-04-27 21:50

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0007_manager_location_alter_merchandiser_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
