# Generated by Django 4.0.3 on 2022-04-27 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0008_alter_manager_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone numbers must begin with +2547.... or 07...', regex='^[0-9 \\(\\)]{10,12}$')]),
        ),
        migrations.AlterField(
            model_name='merchandiser',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone numbers must begin with +2547.... or 07...', regex='^[0-9 \\(\\)]{10,12}$')]),
        ),
    ]
