# Generated by Django 4.0.3 on 2022-04-28 06:34

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0010_rename_city_address_city_start_address_city_stop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city_stop',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='location1',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
