# Generated by Django 4.0.3 on 2022-04-28 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0011_alter_address_city_stop_alter_address_location1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='city_start',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='city_stop',
        ),
        migrations.RemoveField(
            model_name='address',
            name='location1',
        ),
    ]
