# Generated by Django 4.0.3 on 2022-04-28 06:39

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0012_rename_city_start_address_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='destination',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='final_location',
            field=location_field.models.plain.PlainLocationField(default='', max_length=63),
        ),
    ]
