# Generated by Django 4.0.3 on 2022-05-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_alter_manager_company_alter_merchandiser_area_and_more'),
        ('route', '0014_remove_address_destination_and_more'),
    ]

    operations = [
    ]
